global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Include rules
rule_files:
  - "connector_rules.yml"

# Include component-specific scrape configs
scrape_configs:

  - job_name: openfactory
    http_sd_configs:
      - url: http://prometheus-metrics-registry:4000/prometheus/targets
        refresh_interval: 30s
