services:
  opcua-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        OPENFACTORY_VERSION: "main"
    image: openfactoryio/opcua_gateway
    environment:
      - GATEWAY_HOST=opcua-gateway
      - COORDINATOR_URL=${COORDINATOR_URL:-http://opcua-coordinator:8000}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KSQLDB_URL=${KSQLDB_URL}
      - OPCUA_GATEWAY_LOG_LEVEL=${OPCUA_GATEWAY_LOG_LEVEL:-INFO}
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - factory-net

  opcua-coordinator:
    build:
      context: ./coordinator
      dockerfile: Dockerfile
      args:
        OPENFACTORY_VERSION: "main"
    image: openfactoryio/opcua_coordinator
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - factory-net

networks:

    factory-net:
      external: true