# -----------------------------------------------------------------------------
# 🐳 Docker Compose file for OPC UA Connector (OpenFactory)
#
# This file defines the services required to run the OPC UA Connector stack:
# 1. opcua-coordinator   - Orchestrates device assignments across gateways
# 2. opcua-gateway       - Connects to OPC UA servers, monitors devices, and
#                          streams data to OpenFactory via Kafka
#
# Both services are connected through the 'factory-net' Docker network.
#
# Usage (local):
#   # Start services
#   docker compose up -d
#
#   # Stop services
#   docker compose down
#
# Usage (docker swarm):
#   # Source environment variables for an .env file
#   set -a && source .env && set +a
#   # Deploy the stack
#   docker stack deploy -c docker-compose.yml opcua-connector
#
#   # Remove stack
#   docker stack rm opcua-connector
#
# Environment variables:
#   COORDINATOR_URL          URL of the coordinator (default: http://opcua-coordinator:8000)
#   KAFKA_BROKER             Kafka bootstrap server (required)
#   KSQLDB_URL               ksqlDB URL (required)
#   OPCUA_GATEWAY_LOG_LEVEL  Log level (optional, default: INFO)
#
# Ports:
#   Coordinator API: 8000
#   Gateway API:     8001
#
# External network required:
#   factory-net
# -----------------------------------------------------------------------------

services:
  opcua-gateway:
    image: openfactoryio/opcua-gateway
    environment:
      - GATEWAY_HOST=opcua-gateway
      - COORDINATOR_URL=${COORDINATOR_URL:-http://opcua-coordinator:8000}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KSQLDB_URL=${KSQLDB_URL}
      - OPCUA_GATEWAY_LOG_LEVEL=${OPCUA_GATEWAY_LOG_LEVEL:-INFO}
    ports:
      - "8001:8001"
    networks:
      - factory-net

  opcua-coordinator:
    image: openfactoryio/opcua-coordinator
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KSQLDB_URL=${KSQLDB_URL}
    ports:
      - "8000:8000"
    networks:
      - factory-net

networks:

    factory-net:
      external: true
